### ISSUE TITLE
Cannot Compile HTTPD mod_proxy_cluster module

### ISSUE THREAD

**Issue by ozziej** [modcluster/mod_cluster#397]
When running make inside the latest release of **1.3.11.Final** the native/mod_proxy_cluster
Fails with the below error on Linux 
After running 
./buildconf
./configure --with-apxs=/usr/sbin/apxs
./make
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -pthread  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wformat-security -fno-strict-aliasing  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE    -I/usr/include/httpd -I. -I/usr/include/apr-1 -I../include -prefer-pic -c mod_proxy_cluster.c && touch mod_proxy_cluster.slo
mod_proxy_cluster.c: In function ‘init_conn_pool’:
mod_proxy_cluster.c:237: warning: unused variable ‘cp’
mod_proxy_cluster.c: In function ‘internal_find_best_byrequests’:
mod_proxy_cluster.c:2393: error: ‘pptr’ undeclared (first use in this function)
mod_proxy_cluster.c:2393: error: (Each undeclared identifier is reported only once
mod_proxy_cluster.c:2393: error: for each function it appears in.)
mod_proxy_cluster.c:2395: error: ‘proxy_worker_shared’ undeclared (first use in this function)
mod_proxy_cluster.c:2395: error: expected expression before ‘)’ token
mod_proxy_cluster.c: In function ‘proxy_cluster_post_config’:
mod_proxy_cluster.c:2899: error: ‘proxy_worker_shared’ undeclared (first use in this function)
make: *** [mod_proxy_cluster.slo] Error 1

The above process works fine with **1.3.10.Final**

Versions 
$ apachectl -v
Server version: Apache/2.2.15 (Unix)
Server built:   Jun 19 2018 15:45:13

httpd-2.2.15-69.el6.centos.x86_64
httpd-devel-2.2.15-69.el6.centos.x86_64
gcc-4.4.7-23.el6.x86_64
make-3.81-23.el6.x86_64

**Comment by dsartzet** [comment]
Hello @ozziej, 
Can you please try with this patch [mod_proxy_cluster#397.txt](https://github.com/modcluster/mod_cluster/files/3486559/mod_proxy_cluster.397.txt) and let me know if it works for you?

Thanks

**Comment by Karm** [comment]
@dsartzet we deliberately removed support for such old httpd in the past.  Search Jboss mod_cluster forum for details.    I do not think we can accept this to 1.3.x and definitely not to master.   Besides, I do not think it won't be the only change needed to reintorduce httpd 2.2.15 safely.

**Comment by rhusar** [comment]
2.2.15 is almost a decade old release, we certainly do not want to support this and entire 2.2.x is end-of-lived already.
